project:
  type: website
  output-dir: docs
  resources: gitlab-ci.yml
  post-render: date.py
website:
  back-to-top-navigation: true
  reader-mode: true
  page-navigation: true
  favicon: path/to/favicon.ico
  title: MY BLOGS

  navbar:
    type: grid
    right:
      - About.qmd
      - Research Overview.qmd
      - icon: github
        href: 'https://github.com/'
      - icon: twitter
        href: 'https://twitter.com'
      - icon: facebook
        href: 'https://www.facebook.com/heba.nsair'
format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 600px
      margin-width: 450px
      gutter-width: 1.5em
    theme: Darkly
editor: visual





