{
  "hash": "12af5bd00662bc7d107ce69144c6a630",
  "result": {
    "markdown": "---\ntitle: \"The Dynamics of City Residency Preferences, A Deep Dive into Income_Residential Location Choices\"\nsubtitle: \"Linear Regression vs. non_Linear Regression\"\nauthor: \"Heba Nusair\"\ndate: \"2023-11-06\"\ncategories: [news, code, analysis]\nimage: \"image.jpg\"\n---\n\n### **Introduction**\n\nIn the dynamic realm of urban living choices, understanding the factors influencing our habitat preferences is crucial. We embarked on a data-driven journey to explore one such factor -- income. Our goal was simple yet profound: to discern how variations in income affect preferences for living areas. For this, we turned to the ever-reliable tools of machine learning, specifically linear regression.\n\n### **The Study at a Glance**\n\nOur dataset encapsulated responses from individuals, detailing their income levels and preferred living areas -- be it the bustling city center, the vibrant urban zones, the serene suburban areas, or the tranquil rural landscapes. Our approach was straightforward:\n\n1.  We transformed **income** into a continuous scale, assigning monetary values to income brackets.\n\n2.  We converted **living area preferences** into a single, ordinal dependent variable.\n\n3.  We employed linear regression to model the relationship between these two variables.\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.metrics import mean_squared_error, r2_score\nimport matplotlib.pyplot as plt\nimport numpy as np\n\n# Load the dataset\ndata = pd.read_excel('Linear regression_WOS.xlsx')\n\n# Drop rows with NaN values in the area preference and income columns\ndata.dropna(subset=['City_center', 'Urban_area', 'Suburban_area', 'Rural_area', 'Monthly_income'], inplace=True)\n\n# Convert the area preferences into a single ordinal dependent variable\narea_to_number = {'City_center': 1, 'Urban_area': 2, 'Suburban_area': 3, 'Rural_area': 4}\ndata['living_area_preference'] = data[['City_center', 'Urban_area', 'Suburban_area', 'Rural_area']].idxmin(axis=1).map(area_to_number)\n\n# Convert income to a continuous scale based on the provided income brackets\nincome_mapping = {1.0: 625, 2.0: 2292, 3.0: 5000, 4.0: 6666}  # Adjust as needed\ndata['continuous_income'] = data['Monthly_income'].map(income_mapping)\n\n# Drop the original area preference columns and the 'Monthly Income' column\ndata.drop(columns=['City_center', 'Urban_area', 'Suburban_area', 'Rural_area', 'Monthly_income'], inplace=True)\n\n# Ensure no NaN values in 'continuous_income'\ndata.dropna(subset=['continuous_income'], inplace=True)\n\n# Scale the income feature\nscaler = StandardScaler()\ndata['scaled_income'] = scaler.fit_transform(data[['continuous_income']])\n\n# Prepare the features and target variable for modeling\nX = data[['scaled_income']]\ny = data['living_area_preference']\n\n# Split the data into training and testing sets\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Create and train the linear regression model\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\n\n# Predict on the test data\ny_pred = model.predict(X_test)\n\n# Evaluate the model's performance\nmse = mean_squared_error(y_test, y_pred)\nr2 = r2_score(y_test, y_pred)\n\n# Output the performance metrics\nprint(f'Mean Squared Error: {mse}')\nprint(f'R-squared: {r2}')\n\n# Plotting modifications start here\n# Extract the original income values corresponding to the test set\noriginal_income_test = X_test.index.map(lambda idx: data.loc[idx, 'continuous_income'])\n\n# Plotting with original income values\nplt.scatter(original_income_test, y_test, color='black', label='Actual Data')\nplt.scatter(original_income_test, y_pred, color='red', label='Predicted Data', alpha=0.5)\n\n# Optionally, create a more continuous line for predictions (optional, for visual enhancement)\nsorted_order = np.argsort(original_income_test)\nplt.plot(np.array(original_income_test)[sorted_order], np.array(y_pred)[sorted_order], color='blue', linewidth=2, label='Regression Line')\n\nplt.xlabel('Monthly income')\nplt.ylabel('Moving index_ from City Center to Rural Area')\nplt.title('Income vs Living Area Preference Linear Regression')\nplt.legend()\nplt.show()\n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean Squared Error: 1.2229590696534407\nR-squared: -0.0034801764611527286\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-2-output-2.png){width=589 height=449}\n:::\n:::\n\n\n### **Unveiling the Results**\n\nThe outcomes of our analysis were both intriguing and enlightening:\n\n-   **Mean Squared Error (MSE):** The MSE stood at 1.2229590696534407. This figure, in isolation, hinted at some variance between the predicted and actual preferences. However, this is only one piece of the puzzle.\n\n-   **R-squared Value:** Here's where the plot thickens. The R-squared value, at -0.0034801764611527286, raised eyebrows. This negative value suggested that the linear model failed to capture the essence of the relationship between income and living area preference. What does this mean? Simply put, the linear regression model we deployed might not be the right fit for this specific analysis.\n\n### **Interpreting the Outcome**\n\nThis unexpected twist in our narrative compels us to introspect and question. Here are a few takeaways and considerations:\n\n-   **Non-linear Relationships:** Perhaps the bond between income and living area preference isn't a straight line but a curve or a more complex shape. Linear regression, with its assumption of linearity, might not be adept at capturing such nuances.\n\n-   **Missing Puzzle Pieces:** It's plausible that other influential factors, not included in our current model, play a significant role in shaping living area preferences.\n\n-   **Data Reflection:** The integrity and representativeness of our data demand scrutiny. Are there outliers skewing our results? Have we translated income brackets into continuous variables accurately?\n\n### **Moving Forward: A Path of Exploration**\n\nOur findings open new avenues for exploration. Alternative modeling techniques, like logistic regression or including additional variables, might offer deeper insights. Further, a comprehensive review and possible expansion of our dataset could pave the way for a more accurate portrayal of the intricate relationship between income and living area preferences.\n\n### **Conclusion**\n\nOur journey in unraveling the ties between income and living area preference has been a revealing one. While the current model may not have provided the clarity we sought, it has undoubtedly shed light on the complexities of urban living choices and the path forward in our analytical endeavors.\n\n",
    "supporting": [
      "index_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}